<?php

namespace App\Domain\Printing\Services;

class EscPosConverter
{
    public const ESC = "\x1B";

    public const GS = "\x1D";

    /**
     * Convert an order and template context into a raw ESC/POS binary command stream.
     *
     * @param  array<string, mixed>  $context  Context generated by DocumentTemplateRenderer
     * @param array{
     *     paper_width?: string,
     *     cut_paper?: bool,
     *     drawer_kick?: bool
     * } $options
     * @return string Binary byte stream
     */
    /**
     * Convert plain text or preformatted document into ESC/POS byte sequence.
     *
     * @param array{
     *     cut_paper?: bool,
     *     kick_drawer?: bool,
     *     drawer_kick?: bool,
     *     paper_width?: string
     * } $options
     */
    public function textToEscPos(string $text, array $options = []): string
    {
        $cutPaper = $options['cut_paper'] ?? true;
        $drawerKick = $options['kick_drawer'] ?? $options['drawer_kick'] ?? false;

        $out = self::ESC.'@'; // \x1B\x40

        if ($drawerKick) {
            $out .= self::ESC."p\x00\x19\xFA"; // \x1B\x70\x00...
        }

        $out .= $text;

        $out .= "\n\n\n";
        if ($cutPaper) {
            $out .= self::GS."V\x00"; // \x1D\x56\x00
        }

        return $out;
    }

    public function convert(array $context, array $options = []): string
    {
        $paperWidth = $options['paper_width'] ?? '80mm';
        $cutPaper = $options['cut_paper'] ?? true;
        $drawerKick = $options['drawer_kick'] ?? false;

        $maxChars = ($paperWidth === '58mm') ? 32 : 48;
        $out = '';

        // 1. Initialize printer
        $out .= self::ESC.'@';

        // 2. Cash drawer kick (if enabled)
        if ($drawerKick) {
            $out .= self::ESC."p\x00\x19\xFA";
        }

        // 3. Header: Center aligned, Double Height/Width
        $out .= self::ESC."a\x01"; // Center align
        $out .= self::ESC."E\x01"; // Bold on
        $out .= self::GS."!\x11"; // Double size
        $out .= ($context['organization.name'] ?? 'ERPlannet')."\n";
        $out .= self::GS."!\x00"; // Normal size
        $out .= self::ESC."E\x00"; // Bold off

        if (! empty($context['branch.name'])) {
            $out .= $context['branch.name']."\n";
        }
        if (! empty($context['branch.address'])) {
            $out .= $context['branch.address']."\n";
        }

        $out .= str_repeat('-', $maxChars)."\n";

        // 4. Meta Information: Left aligned
        $out .= self::ESC."a\x00"; // Left align
        $out .= $this->formatRow('Order / Համար:', (string) ($context['order.number'] ?? ''), $maxChars);
        $out .= $this->formatRow('Date / Ամսաթիվ:', (string) ($context['order.created_at'] ?? ''), $maxChars);

        if (! empty($context['customer.name'])) {
            $out .= $this->formatRow('Customer / Հաճախորդ:', (string) $context['customer.name'], $maxChars);
        }
        if (! empty($context['customer.tax_id']) && $context['customer.tax_id'] !== 'N/A') {
            $out .= $this->formatRow('TIN / ՀՎՀՀ:', (string) $context['customer.tax_id'], $maxChars);
        }

        $out .= str_repeat('-', $maxChars)."\n";

        // 5. Line Items Table
        $items = $context['items'] ?? [];
        foreach ($items as $it) {
            $itemName = (string) $it['name'];
            $qty = $it['quantity'].' '.($it['unit'] ?? '');
            $price = number_format((float) $it['unit_price'], 0);
            $total = number_format((float) $it['total'], 0).' AMD';

            $out .= self::ESC."E\x01";
            $out .= $itemName."\n";
            $out .= self::ESC."E\x00";

            $lineDetail = "  {$qty} x {$price}";
            $out .= $this->formatRow($lineDetail, $total, $maxChars);
        }

        $out .= str_repeat('=', $maxChars)."\n";

        // 6. Totals & Balances
        $out .= $this->formatRow('Subtotal / Միջանկյալ:', (string) ($context['order.subtotal'] ?? ''), $maxChars);

        if (! empty($context['order.discount_total']) && (float) filter_var($context['order.discount_total'], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION) > 0) {
            $out .= $this->formatRow('Discount / Զեղչ:', '-'.$context['order.discount_total'], $maxChars);
        }

        if (! empty($context['order.delivery_fee']) && (float) filter_var($context['order.delivery_fee'], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION) > 0) {
            $out .= $this->formatRow('Delivery / Առաքում:', (string) $context['order.delivery_fee'], $maxChars);
        }

        if (! empty($context['order.tax_total']) && (float) filter_var($context['order.tax_total'], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION) > 0) {
            $out .= $this->formatRow('VAT (20%) / ԱԱՀ:', (string) $context['order.tax_total'], $maxChars);
        }

        // Grand Total: Bold, Double Height
        $out .= self::ESC."E\x01";
        $out .= self::GS."!\x01"; // Double height
        $out .= $this->formatRow('TOTAL / ԸՆԴԱՄԵՆԸ:', (string) ($context['order.grand_total'] ?? ''), $maxChars);
        $out .= self::GS."!\x00";
        $out .= self::ESC."E\x00";

        $out .= str_repeat('-', $maxChars)."\n";

        // 7. Payment Info & Footer
        if (! empty($context['order.payment_method'])) {
            $out .= $this->formatRow('Payment / Վճարում:', (string) $context['order.payment_method'], $maxChars);
        }
        if (! empty($context['order.amount_paid'])) {
            $out .= $this->formatRow('Paid / Վճարված:', (string) $context['order.amount_paid'], $maxChars);
        }

        $out .= "\n";
        $out .= self::ESC."a\x01"; // Center align
        $out .= ($context['order.notes'] ?? 'Thank you for your purchase!')."\n\n";

        // Feed & Cut Paper
        $out .= "\n\n\n";
        if ($cutPaper) {
            $out .= self::GS."V\x41\x00"; // Full cut
        }

        return $out;
    }

    /**
     * Format a left-label and right-value row matching printer paper character width.
     */
    protected function formatRow(string $left, string $right, int $width): string
    {
        $leftLen = mb_strlen($left, 'UTF-8');
        $rightLen = mb_strlen($right, 'UTF-8');

        $spaces = $width - ($leftLen + $rightLen);
        if ($spaces < 1) {
            $spaces = 1;
        }

        return $left.str_repeat(' ', $spaces).$right."\n";
    }
}
